export { default as Icon } from './Icon'
export { default as AssistIcon } from './AssistIcon'
export { default as GoalIcon } from './GoalIcon'
export { default as MissedPenaltyIcon } from './MissedPenaltyIcon'
export { default as OwnGoalIcon } from './OwnGoalIcon'
export { default as PenaltyGoalIcon } from './PenaltyGoalIcon'
export { default as RedCardIcon } from './RedCardIcon'
export { default as SavedPenaltyIcon } from './SavedPenaltyIcon'
export { default as SecondYellowCardIcon } from './SecondYellowCardIcon'
export { default as SubstitutionIcon } from './SubstitutionIcon'
export { default as YellowCardIcon } from './YellowCardIcon'
export type { AppIconName } from './registry'
