# English country names (from Wikipedia venues) -> Polish names in DB
COUNTRY_MAPPING = {
    'Poland': 'Polska',
    'United States': 'Stany Zjednoczone',
    'United Arab Emirates': 'Zjednoczone Emiraty Arabskie',
    'Turkey': 'Turcja',
    'Thailand': 'Tajlandia',
    'Spain': 'Hiszpania',
    'France': 'Francja',
    'Germany': 'Niemcy',
    'Austria': 'Austria',
    'Italy': 'Włochy',
    'Portugal': 'Portugalia',
    'Ukraine': 'Ukraina',
    'Russia': 'Rosja',
    'Kazakhstan': 'Kazachstan',
    'Azerbaijan': 'Azerbejdżan',
    'Armenia': 'Armenia',
    'Georgia': 'Gruzja',
    'Moldova': 'Mołdawia',
    'Romania': 'Rumunia',
    'Bulgaria': 'Bułgaria',
    'Serbia': 'Serbia',
    'Croatia': 'Chorwacja',
    'Bosnia and Herzegovina': 'Bośnia i Hercegowina',
    'Montenegro': 'Czarnogóra',
    'Slovenia': 'Słowenia',
    'Slovakia': 'Słowacja',
    'Czech Republic': 'Czechy',
    'Poland': 'Polska',
    'Hungary': 'Węgry',
    'Romania': 'Rumunia',
    'Bulgaria': 'Bułgaria',
    'Greece': 'Grecja',
    'Cyprus': 'Cypr',
    'Malta': 'Malta',
    'Denmark': 'Dania',
    'Sweden': 'Szwecja',
    'Norway': 'Norwegia',
    'Finland': 'Finlandia',
    'Estonia': 'Estonia',
    'Latvia': 'Łotwa',
    'Lithuania': 'Litwa',
    'Belarus': 'Białoruś',
    'Belgium': 'Belgia',
    'Netherlands': 'Holandia',
    'Luxembourg': 'Luksemburg',
    'Switzerland': 'Szwajcaria',
    'Iceland': 'Islandia',
    'Ireland': 'Irlandia',
        'Republic of Ireland': 'Irlandia',
    'Northern Ireland': 'Irlandia Północna',
    'England': 'Anglia',
    'Scotland': 'Szkocja',
    'Wales': 'Walia',
    'South Korea': 'Korea Południowa',
    'North Korea': 'Korea Północna',
    'Japan': 'Japonia',
    'China': 'Chiny',
    'India': 'Indie',
    'Pakistan': 'Pakistan',
    'Bangladesh': 'Bangladesz',
    'Vietnam': 'Wietnam',
    'Cambodia': 'Kambodża',
    'Laos': 'Laos',
    'Myanmar': 'Birma',
    'Malaysia': 'Malezja',
    'Singapore': 'Singapur',
    'Indonesia': 'Indonezja',
    'Philippines': 'Filipiny',
    'Australia': 'Australia',
    'New Zealand': 'Nowa Zelandia',
    'Canada': 'Kanada',
    'Mexico': 'Meksyk',
    'Brazil': 'Brazylia',
    'Argentina': 'Argentyna',
    'Chile': 'Chile',
    'Peru': 'Peru',
    'Colombia': 'Kolumbia',
    'Ecuador': 'Ekwador',
    'Uruguay': 'Urugwaj',
    'Venezuela': 'Wenezuela',
    'Paraguay': 'Paragwaj',
    'Bolivia': 'Boliwia',
    'South Africa': 'Republika Południowej Afryki',
    'Egypt': 'Egipt',
    'Nigeria': 'Nigeria',
    'Kenya': 'Kenia',
    'Ghana': 'Ghana',
    'Ivory Coast': 'Wybrzeże Kości Słoniowej',
    'Cameroon': 'Kamerun',
    'Morocco': 'Maroko',
    'Tunisia': 'Tunezja',
    'Israel': 'Izrael',
    'Saudi Arabia': 'Arabia Saudyjska',
    'Qatar': 'Katar',
    'United Arab Emirates': 'Zjednoczone Emiraty Arabskie',
    'Iran': 'Iran',
    'Iraq': 'Irak',
    'Syria': 'Syria',
    'Lebanon': 'Liban',
    'Jordan': 'Jordania',
    'Palestine': 'Palestyna',
    'San Marino': 'San Marino',
    'Andorra': 'Andora',
    'Liechtenstein': 'Liechtenstein',
    'Monaco': 'Monako',
    'Faroe Islands': 'Wyspy Owcze',
    'North Macedonia': 'Macedonia Północna',
}
